name: Build Singularity Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Apptainer
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:apptainer/ppa
        sudo apt-get update
        sudo apt-get install -y apptainer

    - name: Build Singularity Image
      run: make build

    - name: Test Singularity Image
      run: make test

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | apptainer remote login --username ${{ github.actor }} --password-stdin oras://ghcr.io

    - name: Push image to GitHub Container Registry
      run: apptainer push singularity_dask_zarr.sif oras://ghcr.io/${{ github.repository }}:latest