name: Build Singularity Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Apptainer
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:apptainer/ppa
        sudo apt-get update
        sudo apt-get install -y apptainer

    - name: Build Singularity Image
      run: |
        sudo apptainer build singularity_dask_zarr.sif Singularity.def
