name: Build Singularity Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Apptainer
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:apptainer/ppa
        sudo apt-get update
        sudo apt-get install -y apptainer

    - name: Build Singularity Image
      run: |
        sudo apptainer build singularity_dask_zarr.sif Singularity.def

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Convert and Tag Image
      run: |
        sudo apptainer build --force docker-image://ghcr.io/${{ github.repository }}:latest singularity_dask_zarr.sif
        docker tag singularity_dask_zarr.sif ghcr.io/${{ github.repository }}:latest

    - name: Push image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository }}:latest
